-- Enable PostGIS for geospatial features
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. PROFILES
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  city TEXT NOT NULL DEFAULT 'Global',
  color_index INTEGER NOT NULL DEFAULT 0,
  streak INTEGER NOT NULL DEFAULT 0,
  total_km FLOAT NOT NULL DEFAULT 0.0,
  zones_owned INTEGER NOT NULL DEFAULT 0,
  invite_code TEXT UNIQUE NOT NULL,
  profile_picture TEXT,
  last_active_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TERRITORIES (Zones)
CREATE TABLE territories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  geom GEOMETRY(MultiPolygon, 4326) NOT NULL,
  health FLOAT NOT NULL DEFAULT 100.0,
  area_sqm FLOAT GENERATED ALWAYS AS (ST_Area(geom::geography)) STORED,
  captured_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_defended_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX territories_geom_idx ON territories USING GIST (geom);
CREATE INDEX territories_owner_idx ON territories(owner_id);

-- 3. RUNS
CREATE TABLE runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  start_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  end_time TIMESTAMP WITH TIME ZONE,
  distance_km FLOAT DEFAULT 0.0,
  duration_seconds INTEGER DEFAULT 0,
  is_valid BOOLEAN DEFAULT TRUE,
  validation_reason TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX runs_user_idx ON runs(user_id);
CREATE INDEX runs_status_idx ON runs(status);

-- 4. RUN POINTS
CREATE TABLE run_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  geom GEOMETRY(Point, 4326) NOT NULL,
  speed FLOAT NOT NULL DEFAULT 0.0,
  accuracy FLOAT NOT NULL,
  heading FLOAT,
  is_mocked BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX run_points_geom_idx ON run_points USING GIST (geom);
CREATE INDEX run_points_run_id_idx ON run_points(run_id);
CREATE INDEX run_points_timestamp_idx ON run_points(timestamp DESC);

-- 5. TERRITORY EVENTS
CREATE TABLE territory_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  territory_id UUID REFERENCES territories(id) ON DELETE SET NULL,
  attacker_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  defender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  damage_amount FLOAT DEFAULT 0.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX territory_events_defender_idx ON territory_events(defender_id);

-- 6. FRIENDSHIPS
CREATE TABLE friendships (
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  friend_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (user_id, friend_id)
);

-- ==========================================
-- TRIGGERS
-- ==========================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, invite_code)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    substr(md5(random()::text), 1, 6)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- STUB FUNCTIONS
-- ==========================================

CREATE OR REPLACE FUNCTION validate_run_integrity(run_id UUID) 
RETURNS JSON AS $$
BEGIN
  RETURN json_build_object('is_valid', true, 'reason', null);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION process_run_territory(p_run_id UUID, p_user_id UUID) 
RETURNS JSON AS $$
BEGIN
  RETURN json_build_object('success', true, 'captured_area_sqm', 0);
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- RLS SCAFFOLDING
-- ==========================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE territories ENABLE ROW LEVEL SECURITY;
ALTER TABLE runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE run_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE territory_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;

-- Basic RLS Policies
CREATE POLICY "Public profiles are viewable by everyone." 
  ON profiles FOR SELECT TO authenticated USING (true);
  
CREATE POLICY "Users can insert their own profile." 
  ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
  
CREATE POLICY "Users can update own profile." 
  ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Territories: readable by all, writable only by service_role (edge functions)
CREATE POLICY "Territories are viewable by everyone." 
  ON territories FOR SELECT TO authenticated USING (true);

-- Runs
CREATE POLICY "Users view own runs." 
  ON runs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users insert own runs." 
  ON runs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own active runs." 
  ON runs FOR UPDATE TO authenticated USING (auth.uid() = user_id AND status = 'active');

-- Run Points
CREATE POLICY "Users view own run points." 
  ON run_points FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users insert own run points." 
  ON run_points FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id AND EXISTS (SELECT 1 FROM runs WHERE id = run_id AND status = 'active'));

-- Friendships
CREATE POLICY "Users view friendships." 
  ON friendships FOR SELECT TO authenticated USING (auth.uid() = user_id OR auth.uid() = friend_id);
CREATE POLICY "Users manage own friendships." 
  ON friendships FOR ALL TO authenticated USING (auth.uid() = user_id);
